### ISSUE TITLE
int64 support for some operations not supported

### ISSUE THREAD

**Issue by ryx2** [PRBonn/bonnetal#10]
I have installed all the pip packages in a venv, and when I pip list, everything matches up. I also installed pytorch from source. When I attempt to run 

`python3 train.py -c /tank/home/xury1/segmentation/bonnetal/train/tasks/segmentation/config/persons/               mobilenetv2_test.yaml --log /tank/home/xury1/segmentation/bonnetal/train/tasks/segmentation/log -p /dev/null`

INTERFA

> CE:
> config yaml:  /tank/home/xury1/segmentation/bonnetal/train/tasks/segmentation/config/persons/mobilenetv2_test.yaml
> log dir /tank/home/xury1/segmentation/bonnetal/train/tasks/segmentation/log
> model path /dev/null
> eval only False
> No batchnorm False
> ----------
> 
> Commit hash (training version):  b'5368eed'
> ----------
> 
> Opening config file /tank/home/xury1/segmentation/bonnetal/train/tasks/segmentation/config/persons/mobilenetv2_test.yaml
> model folder doesnt exist! Start with random weights...
> Copying files to /tank/home/xury1/segmentation/bonnetal/train/tasks/segmentation/log for further reference.
> Images from:  /tank/home/xury1/segmentation_data/persons/roads_annotated/ds1/train/img
> Labels from:  /tank/home/xury1/segmentation_data/persons/roads_annotated/ds1/train/lbl
> Inference batch size:  3
> Images from:  /tank/home/xury1/segmentation_data/persons/roads_annotated/ds1/valid/img
> Labels from:  /tank/home/xury1/segmentation_data/persons/roads_annotated/ds1/valid/lbl
> Original OS:  32
> New OS:  16.0
> [Decoder] os:  8 in:  32 skip: 32 out:  32
> [Decoder] os:  4 in:  32 skip: 24 out:  24
> [Decoder] os:  2 in:  24 skip: 16 out:  16
> [Decoder] os:  1 in:  16 skip: 3 out:  16
> Using normalized weights as bias for head.
> 
> Couldn't load backbone, using random weights. Error:  [Errno 20] Not a directory: '/dev/null/backbone'
> Couldn't load decoder, using random weights. Error:  [Errno 20] Not a directory: '/dev/null/segmentation_decoder'
> Couldn't load head, using random weights. Error:  [Errno 20] Not a directory: '/dev/null/segmentation_head'
> Total number of parameters:  2154794
> Total number of parameters requires_grad:  2154794
> Param encoder  1812800
> Param decoder  341960
> Param head  34
> Training in device:  cuda
> /tank/home/xury1/segmentation/bonnetal/train/tasks/segmentation/bonnetal/lib/python3.5/site-packages/torch/optim/lr_scheduler.py:100: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
>   "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
> [IOU EVAL] IGNORE:  tensor([], dtype=torch.int64)
> [IOU EVAL] INCLUDE:  tensor([0, 1])
> Traceback (most recent call last):
>   File "train.py", line 118, in <module>
>     trainer.train()
>   File "../../tasks/segmentation/modules/trainer.py", line 302, in train
>     scheduler=self.scheduler)
>   File "../../tasks/segmentation/modules/trainer.py", line 494, in train_epoch
>     evaluator.addBatch(output.argmax(dim=1), target)
>   File "../../tasks/segmentation/modules/ioueval.py", line 42, in addBatch
>     tuple(idxs), self.ones, accumulate=True)
> RuntimeError: "embedding_backward" not implemented for 'Long'

**Comment by ryx2** [comment]
I should also include my yaml file:

```
# training parameters
train:
  loss: "xentropy"       # must be either xentropy or iou
  max_epochs: 300
  max_lr: 0.01           # sgd learning rate max
  min_lr: 0.001          # warmup initial learning rate
  up_epochs: 0.5         # warmup during first XX epochs (can be float)
  down_epochs:  30       # warmdown during second XX epochs  (can be float)
  max_momentum: 0.9      # sgd momentum max when lr is mim
  min_momentum: 0.85     # sgd momentum min when lr is max
  final_decay: 0.995     # learning rate decay per epoch after initial cycle (from min lr)
  w_decay: 0.0005        # weight decay
  batch_size: 5          # batch size
  report_batch: 1        # every x batches, report loss
  report_epoch: 1        # every x epochs, report validation set
  save_summary: False    # Summary of weight histograms for tensorboard
  save_imgs: True        # False doesn't save anything, True saves some 
                         # sample images (one per batch of the last calculated batch)
                         # in log folder
  avg_N: 3               # average the N best models
  crop_prop:
    height: 480
    width: 480

# backbone parameters
backbone:
  name: "mobilenetv2"
  dropout: 0.02
  dropout: 0.02
  bn_d: 0.05
  OS: 16 # output stride
  train: True # train backbone?
  extra:
    width_mult: 1.0
    shallow_feats: True # get features before the last layer (mn2)

decoder:
  name: "aspp_progressive"
  dropout: 0.02
  bn_d: 0.05
  train: True # train decoder?
  extra:
    aspp_channels: 32
    last_channels: 16

# classification head parameters
head:
  name: "segmentation"
  dropout: 0.1

# dataset (to find parser)
dataset:
  name: "persons"
  location: "/tank/home/xury1/segmentation_data/persons/roads_annotated/ds1/"
  workers: 3 # number of threads to get data
  img_means: #rgb
    - 0.46992042
    - 0.45250652
    - 0.42510188
  img_stds: #rgb
    - 0.29184756
    - 0.28221624
    - 0.29719201
  img_prop:
    width: 640
    height: 480
    depth: 3
  labels:
    0: 'background'
    1: 'person'
  labels_w:
    0: 1.0
    1: 1.0
  color_map: # bgr
    0: [0,0,0]
    1: [0,255,0]
```
Where the imgs and lbl's in that dataset folder are float32's and uint8, respectively
